DROP INDEX `customer_branches_branch_id_idx`;--> statement-breakpoint
ALTER TABLE `customer_branches` ADD `active` integer DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `customer_branches` ADD `deactivated_at` integer;--> statement-breakpoint
ALTER TABLE `customer_branches` ADD `updated_at` integer;--> statement-breakpoint
ALTER TABLE `customer_branches` ADD `updated_by` text;--> statement-breakpoint
CREATE INDEX `customer_branches_branch_id_customer_id_idx` ON `customer_branches` (`branch_id`,`customer_id`);--> statement-breakpoint
DROP INDEX `seller_branches_branch_id_idx`;--> statement-breakpoint
ALTER TABLE `seller_branches` ADD `active` integer DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `seller_branches` ADD `deactivated_at` integer;--> statement-breakpoint
ALTER TABLE `seller_branches` ADD `updated_at` integer;--> statement-breakpoint
ALTER TABLE `seller_branches` ADD `updated_by` text;--> statement-breakpoint
CREATE INDEX `seller_branches_branch_id_seller_id_idx` ON `seller_branches` (`branch_id`,`seller_id`);--> statement-breakpoint
ALTER TABLE `branches` ADD `name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `customers` ADD `legal_name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `customers` ADD `trade_name_key` text;--> statement-breakpoint
ALTER TABLE `economic_groups` ADD `name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `product_subgroups` ADD `name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `retail_networks` ADD `name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `sellers` ADD `name_key` text DEFAULT '' NOT NULL;--> statement-breakpoint

-- Backfill determinístico das chaves de busca para linhas já existentes (as novas são gravadas pelo
-- serviço com searchKey). Equivale a searchKey para o português: troca as letras acentuadas pela
-- base e põe em maiúsculas (upper() do SQLite só cobre ASCII, por isso a troca vem antes). Os
-- nomes já foram gravados com trim e espaços colapsados. Diacríticos fora do português ficam
-- como estão até o próximo PATCH do registro.
UPDATE `branches` SET `name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `product_subgroups` SET `name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `retail_networks` SET `name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `economic_groups` SET `name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `sellers` SET `name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `customers` SET `legal_name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`legal_name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N'));--> statement-breakpoint
UPDATE `customers` SET `trade_name_key` = upper(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(`trade_name`, 'á', 'A'), 'à', 'A'), 'â', 'A'), 'ã', 'A'), 'ä', 'A'), 'Á', 'A'), 'À', 'A'), 'Â', 'A'), 'Ã', 'A'), 'Ä', 'A'), 'é', 'E'), 'è', 'E'), 'ê', 'E'), 'ë', 'E'), 'É', 'E'), 'È', 'E'), 'Ê', 'E'), 'Ë', 'E'), 'í', 'I'), 'ì', 'I'), 'î', 'I'), 'ï', 'I'), 'Í', 'I'), 'Ì', 'I'), 'Î', 'I'), 'Ï', 'I'), 'ó', 'O'), 'ò', 'O'), 'ô', 'O'), 'õ', 'O'), 'ö', 'O'), 'Ó', 'O'), 'Ò', 'O'), 'Ô', 'O'), 'Õ', 'O'), 'Ö', 'O'), 'ú', 'U'), 'ù', 'U'), 'û', 'U'), 'ü', 'U'), 'Ú', 'U'), 'Ù', 'U'), 'Û', 'U'), 'Ü', 'U'), 'ç', 'C'), 'Ç', 'C'), 'ñ', 'N'), 'Ñ', 'N')) WHERE `trade_name` IS NOT NULL;
